version: '3.8'
services:
  proxy:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - 8084:8084
      - 9099:80
    volumes:
      - /mnt/shared/haproxy:/usr/local/etc/haproxy
    networks:
      - net
      - emoney_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          
  ha-web:
    image: harbor.hellking.dev/library/nginx-proxy:0.0.1
    networks:
      - net
      - traefik_public
    environment:      
      PROXY_MAP: |
        / => haproxy_proxy:8084/
    deploy:
      labels:
        - ingress.host=ha.hocdevops.me
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
            
  ha-emoney:
    image: harbor.hellking.dev/library/nginx-proxy:0.0.1
    networks:
      - net
      - traefik_public
    environment:      
      PROXY_MAP: |
        / => haproxy_proxy/
    deploy:
      labels:
        - ingress.host=ha.emoney.hocdevops.me
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          
networks:
  net:
  emoney_net: 
    external: true
  traefik_public:
    external: true
